exchange: bittrex

type: backtest # live, realtimetest
strategy: peran
tick_duration: 1 # minutes
num_ticks: 6000
tick_start_delay: 30 # minutes

currency_from:
    symbol: ETH
    balance: 1

currency_to:
    symbol: BTC
    balance: 0

sell_on_finish: default #currency symbol or default, where it is the currency with the most value

transaction_fee: 0.0025
