exchange: bittrex

type: backtest # live, realtimetest
strategy: strat1
# start_time: default, asddsa
tick_duration: 1 # minutes
num_ticks: 1000 # max 2000
tick_start_delay: 30 # minutes

currency_from:
    symbol: ETH
    balance: 0

currency_to:
    symbol: BTC
    balance: 1

sell_on_finish: default #currency symbol or default, where it is the currency with the most value

transaction_fee: 0.0025
