exchange: kraken

type: backtest # live, realtimetest
strategy: trendstrat
# start_time: default, asddsa
tick_duration: 60 # minutes
num_ticks: 678 # max 2000
tick_start_delay: 60 # minutes

currency_from:
    symbol: ETH
    balance: 0

currency_to:
    symbol: USD
    balance: 10000

sell_on_finish: default #currency symbol or default, where it is the currency with the most value


transaction_fee: 0.0025
