exchange: gdax

tick_duration: 1 # minutes
num_ticks: 2000
tick_start_delay: 50 # minutes

currency_from:
    symbol: ETH
    balance: 0

currency_to:
    symbol: BTC
    balance: 1

sell_on_finish: BTC

transaction_fee: 0.0025