exchange: bittrex

type: backtest # live, realtimetest
strategy: strat1
tick_duration: 1 # minutes
num_ticks: 1000
tick_start_delay: 30

currency_from:
    symbol: ETH
    balance: 0

currency_to:
    symbol: BTC
    balance: 1

sell_on_finish: BTC

transaction_fee: 0.0025
