exchange: gdax

number_of_ticks: 310
tick_frequency: 1 # minutes
tick_start_delay: 50 # minutes

currency_from:
    symbol: ETH
    balance: 0

currency_to:
    symbol: BTC
    balance: 1

transaction_fee: 0.0025