exchange: gdax

tick_duration: 1 # minutes
num_ticks: 100
tick_start_delay: 50 # minutes

currency_from:
    symbol: ETH
    balance: 1

currency_to:
    symbol: BTC
    balance: 0

sell_on_finish: ETH

transaction_fee: 0.0025